categories:
  UIDS:
    label: 'Blog Extension (blogext):' # (1)
  blogext.pid:
    label: 'Pid (data folder)' # (2)
    parent: UIDS
  blogext.pageid:
    label: 'Page ID (Plugin)'
    parent: UIDS
  blogext.templates:
    label: 'Layouts, Templates, Partials'
    parent: UIDS


settings:
  blog.pid:
    label: 'Pid'
    category: blogext.pid
    type: string
    default: ''

  blog.pageid:
    label: 'Page ID (Plugin)'
    category: blogext.pageid
    type: string
    default: '' 

  blog.templates:
    label: 'TemplateRootPath'
    category: blogext.templates
    type: string
    default: '' 

  blog.partials:
    label: 'PartialRootPath'
    category: blogext.templates
    type: string
    default: '' 

  blog.layouts:
    label: 'LayoutRootPath'
    category: blogext.templates
    type: string
    default: '' 
