blogext:
  view:
    templateRootPath: 'EXT:blogext/Resources/Private/Templates/'
    partialRootPath: 'EXT:blogext/Resources/Private/Partials/'
    layoutRootPath: 'EXT:blogext/Resources/Private/Layouts/' 

