services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  Lanius\Blogext\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Lanius\Blogext\PageTitle\TitleProvider: null
  Lanius\Blogext\Controller\CategorymenuController:
    class: Lanius\Blogext\Controller\CategorymenuController
    tags:
      - name: controller.service_arguments
  Lanius\Blogext\Controller\TagController:
    class: Lanius\Blogext\Controller\TagController
    tags:
      - name: controller.service_arguments
  Lanius\Blogext\Controller\LastController:
    class: Lanius\Blogext\Controller\LastController
    tags:
      - name: controller.service_arguments
  Lanius\Blogext\Backend\Controller\BlogBackendController:
    tags:
      - backend.controller
